// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch_jobs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const advanceBatchPage = `-- name: AdvanceBatchPage :one
UPDATE batch_jobs
SET stashdb_page    = stashdb_page + 1,
    enqueued_count  = $1,
    pending_count   = $2,
    duplicate_count = $3,
    confirmed       = $4,
    updated_at      = NOW()
WHERE id = $5
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at
`

type AdvanceBatchPageParams struct {
	EnqueuedCount  int32     `json:"enqueued_count"`
	PendingCount   int32     `json:"pending_count"`
	DuplicateCount int32     `json:"duplicate_count"`
	Confirmed      bool      `json:"confirmed"`
	ID             uuid.UUID `json:"id"`
}

func (q *Queries) AdvanceBatchPage(ctx context.Context, arg AdvanceBatchPageParams) (BatchJob, error) {
	row := q.db.QueryRow(ctx, advanceBatchPage,
		arg.EnqueuedCount,
		arg.PendingCount,
		arg.DuplicateCount,
		arg.Confirmed,
		arg.ID,
	)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}

const confirmBatch = `-- name: ConfirmBatch :one
UPDATE batch_jobs
SET confirmed    = TRUE,
    confirmed_at = NOW(),
    updated_at   = NOW()
WHERE id = $1
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at
`

func (q *Queries) ConfirmBatch(ctx context.Context, id uuid.UUID) (BatchJob, error) {
	row := q.db.QueryRow(ctx, confirmBatch, id)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}

const createBatchJob = `-- name: CreateBatchJob :one
INSERT INTO batch_jobs (job_id, type, stashdb_entity_id, entity_name)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at
`

type CreateBatchJobParams struct {
	JobID           uuid.UUID   `json:"job_id"`
	Type            string      `json:"type"`
	StashdbEntityID string      `json:"stashdb_entity_id"`
	EntityName      pgtype.Text `json:"entity_name"`
}

func (q *Queries) CreateBatchJob(ctx context.Context, arg CreateBatchJobParams) (BatchJob, error) {
	row := q.db.QueryRow(ctx, createBatchJob,
		arg.JobID,
		arg.Type,
		arg.StashdbEntityID,
		arg.EntityName,
	)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}

const getBatchJob = `-- name: GetBatchJob :one
SELECT id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at FROM batch_jobs WHERE id = $1
`

func (q *Queries) GetBatchJob(ctx context.Context, id uuid.UUID) (BatchJob, error) {
	row := q.db.QueryRow(ctx, getBatchJob, id)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}

const getBatchJobByJobID = `-- name: GetBatchJobByJobID :one
SELECT id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at FROM batch_jobs WHERE job_id = $1
`

func (q *Queries) GetBatchJobByJobID(ctx context.Context, jobID uuid.UUID) (BatchJob, error) {
	row := q.db.QueryRow(ctx, getBatchJobByJobID, jobID)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}

const listBatchJobs = `-- name: ListBatchJobs :many
SELECT id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at FROM batch_jobs ORDER BY created_at DESC
`

func (q *Queries) ListBatchJobs(ctx context.Context) ([]BatchJob, error) {
	rows, err := q.db.Query(ctx, listBatchJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchJob
	for rows.Next() {
		var i BatchJob
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Type,
			&i.StashdbEntityID,
			&i.EntityName,
			&i.TotalSceneCount,
			&i.EnqueuedCount,
			&i.PendingCount,
			&i.DuplicateCount,
			&i.Confirmed,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StashdbPage,
			&i.LastCheckedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatchCounts = `-- name: UpdateBatchCounts :one
UPDATE batch_jobs
SET total_scene_count = $1,
    enqueued_count    = $2,
    pending_count     = $3,
    duplicate_count   = $4,
    stashdb_page      = $5,
    updated_at        = NOW()
WHERE id = $6
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at
`

type UpdateBatchCountsParams struct {
	TotalSceneCount pgtype.Int4 `json:"total_scene_count"`
	EnqueuedCount   int32       `json:"enqueued_count"`
	PendingCount    int32       `json:"pending_count"`
	DuplicateCount  int32       `json:"duplicate_count"`
	StashdbPage     int32       `json:"stashdb_page"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateBatchCounts(ctx context.Context, arg UpdateBatchCountsParams) (BatchJob, error) {
	row := q.db.QueryRow(ctx, updateBatchCounts,
		arg.TotalSceneCount,
		arg.EnqueuedCount,
		arg.PendingCount,
		arg.DuplicateCount,
		arg.StashdbPage,
		arg.ID,
	)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}

const updateBatchEnqueuedCount = `-- name: UpdateBatchEnqueuedCount :one
UPDATE batch_jobs
SET enqueued_count = enqueued_count + $1,
    updated_at     = NOW()
WHERE id = $2
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at
`

type UpdateBatchEnqueuedCountParams struct {
	Delta int32     `json:"delta"`
	ID    uuid.UUID `json:"id"`
}

func (q *Queries) UpdateBatchEnqueuedCount(ctx context.Context, arg UpdateBatchEnqueuedCountParams) (BatchJob, error) {
	row := q.db.QueryRow(ctx, updateBatchEnqueuedCount, arg.Delta, arg.ID)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}

const updateBatchEntityName = `-- name: UpdateBatchEntityName :one
UPDATE batch_jobs SET entity_name = $1, updated_at = NOW() WHERE id = $2 RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at
`

type UpdateBatchEntityNameParams struct {
	EntityName pgtype.Text `json:"entity_name"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateBatchEntityName(ctx context.Context, arg UpdateBatchEntityNameParams) (BatchJob, error) {
	row := q.db.QueryRow(ctx, updateBatchEntityName, arg.EntityName, arg.ID)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}

const updateBatchLastChecked = `-- name: UpdateBatchLastChecked :one
UPDATE batch_jobs
SET last_checked_at = NOW(),
    updated_at      = NOW()
WHERE id = $1
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at, stashdb_page, last_checked_at
`

func (q *Queries) UpdateBatchLastChecked(ctx context.Context, id uuid.UUID) (BatchJob, error) {
	row := q.db.QueryRow(ctx, updateBatchLastChecked, id)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StashdbPage,
		&i.LastCheckedAt,
	)
	return i, err
}
