// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: batch_jobs.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const confirmBatch = `-- name: ConfirmBatch :one
UPDATE batch_jobs
SET confirmed    = TRUE,
    confirmed_at = NOW(),
    updated_at   = NOW()
WHERE id = $1
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at
`

func (q *Queries) ConfirmBatch(ctx context.Context, id uuid.UUID) (BatchJob, error) {
	row := q.db.QueryRow(ctx, confirmBatch, id)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createBatchJob = `-- name: CreateBatchJob :one
INSERT INTO batch_jobs (job_id, type, stashdb_entity_id, entity_name)
VALUES ($1, $2, $3, $4)
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at
`

type CreateBatchJobParams struct {
	JobID           uuid.UUID   `json:"job_id"`
	Type            string      `json:"type"`
	StashdbEntityID string      `json:"stashdb_entity_id"`
	EntityName      pgtype.Text `json:"entity_name"`
}

func (q *Queries) CreateBatchJob(ctx context.Context, arg CreateBatchJobParams) (BatchJob, error) {
	row := q.db.QueryRow(ctx, createBatchJob,
		arg.JobID,
		arg.Type,
		arg.StashdbEntityID,
		arg.EntityName,
	)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBatchJob = `-- name: GetBatchJob :one
SELECT id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at FROM batch_jobs WHERE id = $1
`

func (q *Queries) GetBatchJob(ctx context.Context, id uuid.UUID) (BatchJob, error) {
	row := q.db.QueryRow(ctx, getBatchJob, id)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listBatchJobs = `-- name: ListBatchJobs :many
SELECT id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at FROM batch_jobs ORDER BY created_at DESC
`

func (q *Queries) ListBatchJobs(ctx context.Context) ([]BatchJob, error) {
	rows, err := q.db.Query(ctx, listBatchJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BatchJob
	for rows.Next() {
		var i BatchJob
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.Type,
			&i.StashdbEntityID,
			&i.EntityName,
			&i.TotalSceneCount,
			&i.EnqueuedCount,
			&i.PendingCount,
			&i.DuplicateCount,
			&i.Confirmed,
			&i.ConfirmedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatchCounts = `-- name: UpdateBatchCounts :one
UPDATE batch_jobs
SET total_scene_count = $1,
    enqueued_count    = $2,
    pending_count     = $3,
    duplicate_count   = $4,
    updated_at        = NOW()
WHERE id = $5
RETURNING id, job_id, type, stashdb_entity_id, entity_name, total_scene_count, enqueued_count, pending_count, duplicate_count, confirmed, confirmed_at, created_at, updated_at
`

type UpdateBatchCountsParams struct {
	TotalSceneCount pgtype.Int4 `json:"total_scene_count"`
	EnqueuedCount   int32       `json:"enqueued_count"`
	PendingCount    int32       `json:"pending_count"`
	DuplicateCount  int32       `json:"duplicate_count"`
	ID              uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateBatchCounts(ctx context.Context, arg UpdateBatchCountsParams) (BatchJob, error) {
	row := q.db.QueryRow(ctx, updateBatchCounts,
		arg.TotalSceneCount,
		arg.EnqueuedCount,
		arg.PendingCount,
		arg.DuplicateCount,
		arg.ID,
	)
	var i BatchJob
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.Type,
		&i.StashdbEntityID,
		&i.EntityName,
		&i.TotalSceneCount,
		&i.EnqueuedCount,
		&i.PendingCount,
		&i.DuplicateCount,
		&i.Confirmed,
		&i.ConfirmedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
