// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: config.sql

package queries

import (
	"context"
)

const getAllConfig = `-- name: GetAllConfig :many
SELECT key, value, description, updated_at FROM config ORDER BY key
`

func (q *Queries) GetAllConfig(ctx context.Context) ([]Config, error) {
	rows, err := q.db.Query(ctx, getAllConfig)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Config
	for rows.Next() {
		var i Config
		if err := rows.Scan(
			&i.Key,
			&i.Value,
			&i.Description,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getConfigValue = `-- name: GetConfigValue :one
SELECT value FROM config WHERE key = $1
`

func (q *Queries) GetConfigValue(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getConfigValue, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const setConfigValue = `-- name: SetConfigValue :exec
INSERT INTO config (key, value, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type SetConfigValueParams struct {
	Key   string `json:"key"`
	Value string `json:"value"`
}

func (q *Queries) SetConfigValue(ctx context.Context, arg SetConfigValueParams) error {
	_, err := q.db.Exec(ctx, setConfigValue, arg.Key, arg.Value)
	return err
}

const setConfigValues = `-- name: SetConfigValues :exec
INSERT INTO config (key, value, updated_at)
SELECT UNNEST($1::text[]), UNNEST($2::text[]), NOW()
ON CONFLICT (key) DO UPDATE SET value = EXCLUDED.value, updated_at = NOW()
`

type SetConfigValuesParams struct {
	Keys   []string `json:"keys"`
	Values []string `json:"values"`
}

func (q *Queries) SetConfigValues(ctx context.Context, arg SetConfigValuesParams) error {
	_, err := q.db.Exec(ctx, setConfigValues, arg.Keys, arg.Values)
	return err
}
