// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: downloads.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createDownload = `-- name: CreateDownload :one
INSERT INTO downloads (job_id, sabnzbd_nzo_id, size_bytes)
VALUES ($1, $2, $3)
RETURNING id, job_id, sabnzbd_nzo_id, status, filename, source_path, final_path, size_bytes, created_at, updated_at, completed_at
`

type CreateDownloadParams struct {
	JobID        uuid.UUID   `json:"job_id"`
	SabnzbdNzoID string      `json:"sabnzbd_nzo_id"`
	SizeBytes    pgtype.Int8 `json:"size_bytes"`
}

func (q *Queries) CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, createDownload, arg.JobID, arg.SabnzbdNzoID, arg.SizeBytes)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.SabnzbdNzoID,
		&i.Status,
		&i.Filename,
		&i.SourcePath,
		&i.FinalPath,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const createLocalDownload = `-- name: CreateLocalDownload :one
INSERT INTO downloads (job_id, sabnzbd_nzo_id, source_path, status)
VALUES ($1, '', $2, 'downloading')
RETURNING id, job_id, sabnzbd_nzo_id, status, filename, source_path, final_path, size_bytes, created_at, updated_at, completed_at
`

type CreateLocalDownloadParams struct {
	JobID      uuid.UUID   `json:"job_id"`
	SourcePath pgtype.Text `json:"source_path"`
}

func (q *Queries) CreateLocalDownload(ctx context.Context, arg CreateLocalDownloadParams) (Download, error) {
	row := q.db.QueryRow(ctx, createLocalDownload, arg.JobID, arg.SourcePath)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.SabnzbdNzoID,
		&i.Status,
		&i.Filename,
		&i.SourcePath,
		&i.FinalPath,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDownloadByJobID = `-- name: GetDownloadByJobID :one
SELECT id, job_id, sabnzbd_nzo_id, status, filename, source_path, final_path, size_bytes, created_at, updated_at, completed_at FROM downloads WHERE job_id = $1
`

func (q *Queries) GetDownloadByJobID(ctx context.Context, jobID uuid.UUID) (Download, error) {
	row := q.db.QueryRow(ctx, getDownloadByJobID, jobID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.SabnzbdNzoID,
		&i.Status,
		&i.Filename,
		&i.SourcePath,
		&i.FinalPath,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getDownloadByNzoID = `-- name: GetDownloadByNzoID :one
SELECT id, job_id, sabnzbd_nzo_id, status, filename, source_path, final_path, size_bytes, created_at, updated_at, completed_at FROM downloads WHERE sabnzbd_nzo_id = $1
`

func (q *Queries) GetDownloadByNzoID(ctx context.Context, sabnzbdNzoID string) (Download, error) {
	row := q.db.QueryRow(ctx, getDownloadByNzoID, sabnzbdNzoID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.SabnzbdNzoID,
		&i.Status,
		&i.Filename,
		&i.SourcePath,
		&i.FinalPath,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const getLocalFoundDownloads = `-- name: GetLocalFoundDownloads :many
SELECT d.job_id, d.source_path FROM downloads d
JOIN jobs j ON j.id = d.job_id
WHERE j.status = 'local_found'
`

type GetLocalFoundDownloadsRow struct {
	JobID      uuid.UUID   `json:"job_id"`
	SourcePath pgtype.Text `json:"source_path"`
}

func (q *Queries) GetLocalFoundDownloads(ctx context.Context) ([]GetLocalFoundDownloadsRow, error) {
	rows, err := q.db.Query(ctx, getLocalFoundDownloads)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLocalFoundDownloadsRow
	for rows.Next() {
		var i GetLocalFoundDownloadsRow
		if err := rows.Scan(&i.JobID, &i.SourcePath); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDownloadComplete = `-- name: UpdateDownloadComplete :one
UPDATE downloads
SET filename     = $1,
    source_path  = $2,
    completed_at = NOW(),
    updated_at   = NOW()
WHERE id = $3
RETURNING id, job_id, sabnzbd_nzo_id, status, filename, source_path, final_path, size_bytes, created_at, updated_at, completed_at
`

type UpdateDownloadCompleteParams struct {
	Filename   pgtype.Text `json:"filename"`
	SourcePath pgtype.Text `json:"source_path"`
	ID         uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDownloadComplete(ctx context.Context, arg UpdateDownloadCompleteParams) (Download, error) {
	row := q.db.QueryRow(ctx, updateDownloadComplete, arg.Filename, arg.SourcePath, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.SabnzbdNzoID,
		&i.Status,
		&i.Filename,
		&i.SourcePath,
		&i.FinalPath,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDownloadFinalPath = `-- name: UpdateDownloadFinalPath :one
UPDATE downloads
SET final_path = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, job_id, sabnzbd_nzo_id, status, filename, source_path, final_path, size_bytes, created_at, updated_at, completed_at
`

type UpdateDownloadFinalPathParams struct {
	FinalPath pgtype.Text `json:"final_path"`
	ID        uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateDownloadFinalPath(ctx context.Context, arg UpdateDownloadFinalPathParams) (Download, error) {
	row := q.db.QueryRow(ctx, updateDownloadFinalPath, arg.FinalPath, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.SabnzbdNzoID,
		&i.Status,
		&i.Filename,
		&i.SourcePath,
		&i.FinalPath,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}

const updateDownloadStatus = `-- name: UpdateDownloadStatus :one
UPDATE downloads
SET status     = $1,
    updated_at = NOW()
WHERE id = $2
RETURNING id, job_id, sabnzbd_nzo_id, status, filename, source_path, final_path, size_bytes, created_at, updated_at, completed_at
`

type UpdateDownloadStatusParams struct {
	Status string    `json:"status"`
	ID     uuid.UUID `json:"id"`
}

func (q *Queries) UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) (Download, error) {
	row := q.db.QueryRow(ctx, updateDownloadStatus, arg.Status, arg.ID)
	var i Download
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.SabnzbdNzoID,
		&i.Status,
		&i.Filename,
		&i.SourcePath,
		&i.FinalPath,
		&i.SizeBytes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompletedAt,
	)
	return i, err
}
