// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: job_events.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createJobEvent = `-- name: CreateJobEvent :one
INSERT INTO job_events (job_id, event_type, payload)
VALUES ($1, $2, $3)
RETURNING id, job_id, event_type, payload, created_at
`

type CreateJobEventParams struct {
	JobID     uuid.UUID `json:"job_id"`
	EventType string    `json:"event_type"`
	Payload   []byte    `json:"payload"`
}

func (q *Queries) CreateJobEvent(ctx context.Context, arg CreateJobEventParams) (JobEvent, error) {
	row := q.db.QueryRow(ctx, createJobEvent, arg.JobID, arg.EventType, arg.Payload)
	var i JobEvent
	err := row.Scan(
		&i.ID,
		&i.JobID,
		&i.EventType,
		&i.Payload,
		&i.CreatedAt,
	)
	return i, err
}

const listJobEventsByJobID = `-- name: ListJobEventsByJobID :many
SELECT id, job_id, event_type, payload, created_at FROM job_events
WHERE job_id = $1
ORDER BY id ASC
`

func (q *Queries) ListJobEventsByJobID(ctx context.Context, jobID uuid.UUID) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listJobEventsByJobID, jobID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEvent
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecentGlobalEvents = `-- name: ListRecentGlobalEvents :many
SELECT id, job_id, event_type, payload, created_at FROM job_events
ORDER BY id DESC
LIMIT $1
`

func (q *Queries) ListRecentGlobalEvents(ctx context.Context, maxResults int32) ([]JobEvent, error) {
	rows, err := q.db.Query(ctx, listRecentGlobalEvents, maxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []JobEvent
	for rows.Next() {
		var i JobEvent
		if err := rows.Scan(
			&i.ID,
			&i.JobID,
			&i.EventType,
			&i.Payload,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
