// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: jobs.sql
// NOTE: manually updated to add CreatePendingApprovalJob

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPendingApprovalJob = `-- name: CreatePendingApprovalJob :one
INSERT INTO jobs (type, status, stashdb_url, parent_batch_id)
VALUES ($1, 'pending_approval', $2, $3)
RETURNING id, type, status, stashdb_url, stashdb_id, parent_batch_id, error_message, retry_count, created_at, updated_at
`

type CreatePendingApprovalJobParams struct {
	Type          string      `json:"type"`
	StashdbUrl    string      `json:"stashdb_url"`
	ParentBatchID pgtype.UUID `json:"parent_batch_id"`
}

func (q *Queries) CreatePendingApprovalJob(ctx context.Context, arg CreatePendingApprovalJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createPendingApprovalJob,
		arg.Type,
		arg.StashdbUrl,
		arg.ParentBatchID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.StashdbUrl,
		&i.StashdbID,
		&i.ParentBatchID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const cancelJob = `-- name: CancelJob :exec
UPDATE jobs
SET status     = 'cancelled',
    updated_at = NOW()
WHERE id = $1
`

func (q *Queries) CancelJob(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, cancelJob, id)
	return err
}

const createJob = `-- name: CreateJob :one
INSERT INTO jobs (type, stashdb_url, stashdb_id, parent_batch_id)
VALUES ($1, $2, $3, $4)
RETURNING id, type, status, stashdb_url, stashdb_id, parent_batch_id, error_message, retry_count, created_at, updated_at
`

type CreateJobParams struct {
	Type          string      `json:"type"`
	StashdbUrl    string      `json:"stashdb_url"`
	StashdbID     pgtype.Text `json:"stashdb_id"`
	ParentBatchID pgtype.UUID `json:"parent_batch_id"`
}

func (q *Queries) CreateJob(ctx context.Context, arg CreateJobParams) (Job, error) {
	row := q.db.QueryRow(ctx, createJob,
		arg.Type,
		arg.StashdbUrl,
		arg.StashdbID,
		arg.ParentBatchID,
	)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.StashdbUrl,
		&i.StashdbID,
		&i.ParentBatchID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJob = `-- name: GetJob :one
SELECT id, type, status, stashdb_url, stashdb_id, parent_batch_id, error_message, retry_count, created_at, updated_at FROM jobs WHERE id = $1
`

func (q *Queries) GetJob(ctx context.Context, id uuid.UUID) (Job, error) {
	row := q.db.QueryRow(ctx, getJob, id)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.StashdbUrl,
		&i.StashdbID,
		&i.ParentBatchID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getJobsForWorker = `-- name: GetJobsForWorker :many
SELECT id, type, status, stashdb_url, stashdb_id, parent_batch_id, error_message, retry_count, created_at, updated_at FROM jobs
WHERE status = $1
ORDER BY created_at ASC
LIMIT $2
FOR UPDATE SKIP LOCKED
`

type GetJobsForWorkerParams struct {
	Status     string `json:"status"`
	MaxResults int32  `json:"max_results"`
}

func (q *Queries) GetJobsForWorker(ctx context.Context, arg GetJobsForWorkerParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, getJobsForWorker, arg.Status, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.StashdbUrl,
			&i.StashdbID,
			&i.ParentBatchID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listJobs = `-- name: ListJobs :many
SELECT id, type, status, stashdb_url, stashdb_id, parent_batch_id, error_message, retry_count, created_at, updated_at FROM jobs
WHERE ($1::text IS NULL OR status = $1::text)
  AND ($2::text IS NULL OR type = $2::text)
ORDER BY created_at DESC
LIMIT $3
`

type ListJobsParams struct {
	Status     pgtype.Text `json:"status"`
	Type       pgtype.Text `json:"type"`
	MaxResults int32       `json:"max_results"`
}

func (q *Queries) ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error) {
	rows, err := q.db.Query(ctx, listJobs, arg.Status, arg.Type, arg.MaxResults)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Job
	for rows.Next() {
		var i Job
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.Status,
			&i.StashdbUrl,
			&i.StashdbID,
			&i.ParentBatchID,
			&i.ErrorMessage,
			&i.RetryCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateJobStatus = `-- name: UpdateJobStatus :one
UPDATE jobs
SET status        = $1,
    error_message = $2,
    updated_at    = NOW()
WHERE id = $3
RETURNING id, type, status, stashdb_url, stashdb_id, parent_batch_id, error_message, retry_count, created_at, updated_at
`

type UpdateJobStatusParams struct {
	Status       string      `json:"status"`
	ErrorMessage pgtype.Text `json:"error_message"`
	ID           uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error) {
	row := q.db.QueryRow(ctx, updateJobStatus, arg.Status, arg.ErrorMessage, arg.ID)
	var i Job
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.Status,
		&i.StashdbUrl,
		&i.StashdbID,
		&i.ParentBatchID,
		&i.ErrorMessage,
		&i.RetryCount,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
