// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type BatchJob struct {
	ID              uuid.UUID          `json:"id"`
	JobID           uuid.UUID          `json:"job_id"`
	Type            string             `json:"type"`
	StashdbEntityID string             `json:"stashdb_entity_id"`
	EntityName      pgtype.Text        `json:"entity_name"`
	TotalSceneCount pgtype.Int4        `json:"total_scene_count"`
	EnqueuedCount   int32              `json:"enqueued_count"`
	PendingCount    int32              `json:"pending_count"`
	DuplicateCount  int32              `json:"duplicate_count"`
	StashdbPage     int32              `json:"stashdb_page"`
	Confirmed       bool               `json:"confirmed"`
	ConfirmedAt     pgtype.Timestamptz `json:"confirmed_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	TagIDs          []byte             `json:"tag_ids"`
}

type Config struct {
	Key         string             `json:"key"`
	Value       string             `json:"value"`
	Description pgtype.Text        `json:"description"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

type Download struct {
	ID           uuid.UUID          `json:"id"`
	JobID        uuid.UUID          `json:"job_id"`
	SabnzbdNzoID string             `json:"sabnzbd_nzo_id"`
	Status       string             `json:"status"`
	Filename     pgtype.Text        `json:"filename"`
	SourcePath   pgtype.Text        `json:"source_path"`
	FinalPath    pgtype.Text        `json:"final_path"`
	SizeBytes    pgtype.Int8        `json:"size_bytes"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
}

type Job struct {
	ID            uuid.UUID          `json:"id"`
	Type          string             `json:"type"`
	Status        string             `json:"status"`
	StashdbUrl    string             `json:"stashdb_url"`
	StashdbID     pgtype.Text        `json:"stashdb_id"`
	ParentBatchID pgtype.UUID        `json:"parent_batch_id"`
	ErrorMessage  pgtype.Text        `json:"error_message"`
	RetryCount    int32              `json:"retry_count"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
}

type JobEvent struct {
	ID        int64              `json:"id"`
	JobID     uuid.UUID          `json:"job_id"`
	EventType string             `json:"event_type"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Scene struct {
	ID              uuid.UUID          `json:"id"`
	JobID           uuid.UUID          `json:"job_id"`
	StashdbSceneID  string             `json:"stashdb_scene_id"`
	Title           string             `json:"title"`
	StudioName      pgtype.Text        `json:"studio_name"`
	StudioSlug      pgtype.Text        `json:"studio_slug"`
	ReleaseDate     pgtype.Date        `json:"release_date"`
	DurationSeconds pgtype.Int4        `json:"duration_seconds"`
	Performers      []byte             `json:"performers"`
	Tags            []byte             `json:"tags"`
	RawResponse     []byte             `json:"raw_response"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
}

type SchemaMigration struct {
	Version   int32              `json:"version"`
	AppliedAt pgtype.Timestamptz `json:"applied_at"`
}

type SearchResult struct {
	ID              uuid.UUID          `json:"id"`
	JobID           uuid.UUID          `json:"job_id"`
	IndexerName     string             `json:"indexer_name"`
	ReleaseTitle    string             `json:"release_title"`
	SizeBytes       pgtype.Int8        `json:"size_bytes"`
	PublishDate     pgtype.Timestamptz `json:"publish_date"`
	DownloadUrl     pgtype.Text        `json:"download_url"`
	NzbID           pgtype.Text        `json:"nzb_id"`
	ConfidenceScore int32              `json:"confidence_score"`
	ScoreBreakdown  []byte             `json:"score_breakdown"`
	IsSelected      bool               `json:"is_selected"`
	SelectedBy      pgtype.Text        `json:"selected_by"`
	SelectedAt      pgtype.Timestamptz `json:"selected_at"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	InfoUrl         pgtype.Text        `json:"info_url"`
}

type StashInstance struct {
	ID        uuid.UUID          `json:"id"`
	Name      string             `json:"name"`
	Url       string             `json:"url"`
	ApiKey    string             `json:"api_key"`
	IsDefault bool               `json:"is_default"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type StudioAlias struct {
	ID        uuid.UUID          `json:"id"`
	Canonical string             `json:"canonical"`
	Alias     string             `json:"alias"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}
