// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CancelJob(ctx context.Context, id uuid.UUID) error
	ConfirmBatch(ctx context.Context, id uuid.UUID) (BatchJob, error)
	CreateAlias(ctx context.Context, arg CreateAliasParams) (StudioAlias, error)
	CreateBatchJob(ctx context.Context, arg CreateBatchJobParams) (BatchJob, error)
	CreateDownload(ctx context.Context, arg CreateDownloadParams) (Download, error)
	CreateJob(ctx context.Context, arg CreateJobParams) (Job, error)
	CreateJobEvent(ctx context.Context, arg CreateJobEventParams) (JobEvent, error)
	CreatePendingApprovalJob(ctx context.Context, arg CreatePendingApprovalJobParams) (Job, error)
	CreateScene(ctx context.Context, arg CreateSceneParams) (Scene, error)
	CreateSearchResult(ctx context.Context, arg CreateSearchResultParams) (SearchResult, error)
	CreateStashInstance(ctx context.Context, arg CreateStashInstanceParams) (StashInstance, error)
	DeleteAlias(ctx context.Context, id uuid.UUID) error
	DeleteSearchResultsByJobID(ctx context.Context, jobID uuid.UUID) error
	DeleteStashInstance(ctx context.Context, id uuid.UUID) error
	GetAliasByAlias(ctx context.Context, alias string) (StudioAlias, error)
	GetAllConfig(ctx context.Context) ([]Config, error)
	GetBatchJob(ctx context.Context, id uuid.UUID) (BatchJob, error)
	GetBatchJobByJobID(ctx context.Context, jobID uuid.UUID) (BatchJob, error)
	GetConfigValue(ctx context.Context, key string) (string, error)
	GetDefaultStashInstance(ctx context.Context) (StashInstance, error)
	GetDownloadByJobID(ctx context.Context, jobID uuid.UUID) (Download, error)
	GetDownloadByNzoID(ctx context.Context, sabnzbdNzoID string) (Download, error)
	GetJob(ctx context.Context, id uuid.UUID) (Job, error)
	GetJobByStashDBID(ctx context.Context, stashdbID pgtype.Text) (Job, error)
	GetJobsForWorker(ctx context.Context, arg GetJobsForWorkerParams) ([]Job, error)
	GetSceneByJobID(ctx context.Context, jobID uuid.UUID) (Scene, error)
	GetSceneByStashDBID(ctx context.Context, stashdbSceneID string) (Scene, error)
	GetSelectedResultByJobID(ctx context.Context, jobID uuid.UUID) (SearchResult, error)
	GetStashInstance(ctx context.Context, id uuid.UUID) (StashInstance, error)
	ListAliases(ctx context.Context) ([]StudioAlias, error)
	ListBatchJobs(ctx context.Context) ([]BatchJob, error)
	ListJobEventsByJobID(ctx context.Context, jobID uuid.UUID) ([]JobEvent, error)
	ListJobs(ctx context.Context, arg ListJobsParams) ([]Job, error)
	ListRecentGlobalEvents(ctx context.Context, maxResults int32) ([]JobEvent, error)
	ListSearchResultsByJobID(ctx context.Context, jobID uuid.UUID) ([]SearchResult, error)
	ListStashInstances(ctx context.Context) ([]StashInstance, error)
	SelectSearchResult(ctx context.Context, arg SelectSearchResultParams) (SearchResult, error)
	SetConfigValue(ctx context.Context, arg SetConfigValueParams) error
	SetConfigValues(ctx context.Context, arg SetConfigValuesParams) error
	SetDefaultStashInstance(ctx context.Context, id uuid.UUID) error
	UpdateBatchCounts(ctx context.Context, arg UpdateBatchCountsParams) (BatchJob, error)
	UpdateBatchEntityName(ctx context.Context, arg UpdateBatchEntityNameParams) (BatchJob, error)
	UpdateDownloadComplete(ctx context.Context, arg UpdateDownloadCompleteParams) (Download, error)
	UpdateDownloadFinalPath(ctx context.Context, arg UpdateDownloadFinalPathParams) (Download, error)
	UpdateDownloadStatus(ctx context.Context, arg UpdateDownloadStatusParams) (Download, error)
	UpdateJobStatus(ctx context.Context, arg UpdateJobStatusParams) (Job, error)
	UpdateStashInstance(ctx context.Context, arg UpdateStashInstanceParams) (StashInstance, error)
}

var _ Querier = (*Queries)(nil)
