// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stash_instances.sql

package queries

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createStashInstance = `-- name: CreateStashInstance :one
INSERT INTO stash_instances (name, url, external_url, api_key, is_default)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, name, url, api_key, is_default, created_at, updated_at, external_url
`

type CreateStashInstanceParams struct {
	Name        string      `json:"name"`
	Url         string      `json:"url"`
	ExternalUrl pgtype.Text `json:"external_url"`
	ApiKey      string      `json:"api_key"`
	IsDefault   bool        `json:"is_default"`
}

func (q *Queries) CreateStashInstance(ctx context.Context, arg CreateStashInstanceParams) (StashInstance, error) {
	row := q.db.QueryRow(ctx, createStashInstance,
		arg.Name,
		arg.Url,
		arg.ExternalUrl,
		arg.ApiKey,
		arg.IsDefault,
	)
	var i StashInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ApiKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalUrl,
	)
	return i, err
}

const deleteStashInstance = `-- name: DeleteStashInstance :exec
DELETE FROM stash_instances WHERE id = $1
`

func (q *Queries) DeleteStashInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteStashInstance, id)
	return err
}

const getDefaultStashInstance = `-- name: GetDefaultStashInstance :one
SELECT id, name, url, api_key, is_default, created_at, updated_at, external_url FROM stash_instances WHERE is_default = TRUE LIMIT 1
`

func (q *Queries) GetDefaultStashInstance(ctx context.Context) (StashInstance, error) {
	row := q.db.QueryRow(ctx, getDefaultStashInstance)
	var i StashInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ApiKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalUrl,
	)
	return i, err
}

const getStashInstance = `-- name: GetStashInstance :one
SELECT id, name, url, api_key, is_default, created_at, updated_at, external_url FROM stash_instances WHERE id = $1
`

func (q *Queries) GetStashInstance(ctx context.Context, id uuid.UUID) (StashInstance, error) {
	row := q.db.QueryRow(ctx, getStashInstance, id)
	var i StashInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ApiKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalUrl,
	)
	return i, err
}

const listStashInstances = `-- name: ListStashInstances :many
SELECT id, name, url, api_key, is_default, created_at, updated_at, external_url FROM stash_instances ORDER BY name
`

func (q *Queries) ListStashInstances(ctx context.Context) ([]StashInstance, error) {
	rows, err := q.db.Query(ctx, listStashInstances)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StashInstance
	for rows.Next() {
		var i StashInstance
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Url,
			&i.ApiKey,
			&i.IsDefault,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ExternalUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setDefaultStashInstance = `-- name: SetDefaultStashInstance :exec
UPDATE stash_instances
SET is_default = (id = $1),
    updated_at = NOW()
`

func (q *Queries) SetDefaultStashInstance(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, setDefaultStashInstance, id)
	return err
}

const updateStashInstance = `-- name: UpdateStashInstance :one
UPDATE stash_instances
SET name         = $1,
    url          = $2,
    external_url = $3,
    api_key      = $4,
    is_default   = $5,
    updated_at   = NOW()
WHERE id = $6
RETURNING id, name, url, api_key, is_default, created_at, updated_at, external_url
`

type UpdateStashInstanceParams struct {
	Name        string      `json:"name"`
	Url         string      `json:"url"`
	ExternalUrl pgtype.Text `json:"external_url"`
	ApiKey      string      `json:"api_key"`
	IsDefault   bool        `json:"is_default"`
	ID          uuid.UUID   `json:"id"`
}

func (q *Queries) UpdateStashInstance(ctx context.Context, arg UpdateStashInstanceParams) (StashInstance, error) {
	row := q.db.QueryRow(ctx, updateStashInstance,
		arg.Name,
		arg.Url,
		arg.ExternalUrl,
		arg.ApiKey,
		arg.IsDefault,
		arg.ID,
	)
	var i StashInstance
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Url,
		&i.ApiKey,
		&i.IsDefault,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ExternalUrl,
	)
	return i, err
}
