// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: studio_aliases.sql

package queries

import (
	"context"

	"github.com/google/uuid"
)

const createAlias = `-- name: CreateAlias :one
INSERT INTO studio_aliases (canonical, alias)
VALUES ($1, $2)
RETURNING id, canonical, alias, created_at
`

type CreateAliasParams struct {
	Canonical string `json:"canonical"`
	Alias     string `json:"alias"`
}

func (q *Queries) CreateAlias(ctx context.Context, arg CreateAliasParams) (StudioAlias, error) {
	row := q.db.QueryRow(ctx, createAlias, arg.Canonical, arg.Alias)
	var i StudioAlias
	err := row.Scan(
		&i.ID,
		&i.Canonical,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAlias = `-- name: DeleteAlias :exec
DELETE FROM studio_aliases WHERE id = $1
`

func (q *Queries) DeleteAlias(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteAlias, id)
	return err
}

const getAliasByAlias = `-- name: GetAliasByAlias :one
SELECT id, canonical, alias, created_at FROM studio_aliases WHERE LOWER(alias) = LOWER($1)
`

func (q *Queries) GetAliasByAlias(ctx context.Context, alias string) (StudioAlias, error) {
	row := q.db.QueryRow(ctx, getAliasByAlias, alias)
	var i StudioAlias
	err := row.Scan(
		&i.ID,
		&i.Canonical,
		&i.Alias,
		&i.CreatedAt,
	)
	return i, err
}

const listAliases = `-- name: ListAliases :many
SELECT id, canonical, alias, created_at FROM studio_aliases ORDER BY canonical, alias
`

func (q *Queries) ListAliases(ctx context.Context) ([]StudioAlias, error) {
	rows, err := q.db.Query(ctx, listAliases)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StudioAlias
	for rows.Next() {
		var i StudioAlias
		if err := rows.Scan(
			&i.ID,
			&i.Canonical,
			&i.Alias,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
