INSERT INTO config (key, value, description) VALUES
    ('prowlarr.url', '', 'Prowlarr base URL'),
    ('prowlarr.api_key', '', 'Prowlarr API key'),
    ('prowlarr.search_limit', '10', 'Max results per indexer per search'),
    ('sabnzbd.url', '', 'SABnzbd base URL'),
    ('sabnzbd.api_key', '', 'SABnzbd API key'),
    ('sabnzbd.category', 'stasharr', 'SABnzbd category for downloads'),
    ('sabnzbd.complete_dir', '', 'SABnzbd complete directory path'),
    ('stashdb.api_key', '', 'StashDB API key'),
    ('matching.auto_threshold', '85', 'Auto-approve confidence threshold'),
    ('matching.review_threshold', '50', 'Minimum confidence for review queue'),
    ('pipeline.worker_resolver_pool', '5', 'Concurrent resolver goroutines'),
    ('pipeline.worker_search_pool', '5', 'Concurrent search goroutines'),
    ('pipeline.worker_download_pool', '3', 'Concurrent download goroutines'),
    ('pipeline.worker_move_pool', '3', 'Concurrent move goroutines'),
    ('pipeline.worker_scan_pool', '3', 'Concurrent scan goroutines'),
    ('pipeline.monitor_poll_interval', '30', 'SABnzbd poll interval in seconds'),
    ('pipeline.stashdb_rate_limit', '5', 'Max StashDB requests per second'),
    ('pipeline.batch_auto_threshold', '40', 'Scenes before batch confirmation required'),
    ('pipeline.max_retries_resolver', '3', 'Max retry attempts for resolve failures'),
    ('pipeline.max_retries_search', '2', 'Max retry attempts for search failures'),
    ('pipeline.max_retries_move', '3', 'Max retry attempts for move failures'),
    ('pipeline.max_retries_scan', '5', 'Max retry attempts for scan failures'),
    ('directory.template', '{studio}/{year}/{title} ({year}).{ext}', 'Directory and filename template'),
    ('directory.performer_max', '3', 'Max performers in template token'),
    ('directory.missing_field_value', '1unknown', 'Fallback for missing metadata fields')
ON CONFLICT (key) DO NOTHING;
